language: node_js
node_js:
- 0.8
before_script: coffee --compile -o js coffee
before_install:
- npm install coffee-script
after_script:
- git status
- git config user.name "tonyfast"
- git config user.email "tony.fast@gmail.com"
- git add .
- git commit -m "Build Coffeescript"
- git status
- git push --force "https://${GH_TOKEN}@$github.com/tonyfast/d3.template.git" master:master > /dev/null 2>&1

env:
  global:
    secure: CiHPKJGq+ydsnXmwW+oO0tYpV5QU5dB1iRHX5jwFAfKAjcr1Bb24QsVkkkOgAS+D8x5a256AlpHtuCFRUzlBUvvABzPfAL15GXyXk/cCMfRa6+F89ElWr5sX5M5k/58iWHBXo3yTdvPhS4wwRCCWkSoeH0/cjOMGaOKpJ/7jcsQ=
